rabbit1:
  image: harbur/rabbitmq-cluster
  hostname: rabbit1
  environment:
    - ERLANG_COOKIE=abcdefg
  ports:
    - "5673:5672"
    - "15673:15672"

rabbit2:
  image: harbur/rabbitmq-cluster
  hostname: rabbit2
  links:
    - rabbit1
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=rabbit1
    - ENABLE_RAM=true
    - RAM_NODE=true
  ports:
    - "5674:5672"
    - "15674:15672"

rabbit3:
  image: harbur/rabbitmq-cluster
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=rabbit1
  ports:
    - "5675:5672"
    - "15675:15672"


haproxy:
  image: haproxy
  volumes:    
    - ./haproxy/:/usr/local/etc/haproxy
  links:
    - rabbit1
    - rabbit2
    - rabbit3
  ports:
    - "15672:15672"
    - "5672:5672"
    - "8080:8080"